-- SELECT DATABASE
USE projeto;
-- DELETE RECORDS FROM pessoa
DELETE FROM pessoa;
-- INSERT INTO pessoa
INSERT INTO pessoa VALUES ('1','1','Roberto','Do Proerd','150042-4','robProd','Roberto123','Roberto@gmail.com','0','Suporte');
INSERT INTO pessoa VALUES ('2','1','Jorge','Da Esquina','130041-2','JorEsqui','Jorge123','Jorge@gmail.com','0','Suporte');
INSERT INTO pessoa VALUES ('3','0','Kaique','Futemma','160046-X','KFutemma','Kaique123','Kaique@gmail.com','0','Aluno');
INSERT INTO pessoa VALUES ('4','0','Luiz','Henrique','160046-7','Acelera','Luiz123','Luiz@gmail.com','0','Aluno');
INSERT INTO pessoa VALUES ('5','0','Guilherme','Gonçalves','160043-5','AlahuAkbar','Gui123','Gui@gmail.com','0','Aluno');
INSERT INTO pessoa VALUES ('6','0','Carlos','Beluzo','160073-X','Beluga','Beluzo123','Beluzo@gmail.com','0','Professor');
INSERT INTO pessoa VALUES ('7','0','Bruno','Bogarin','160016-6','CARALHONOVINHA','Bogarin123','Bogarin@gmail.com','1','Aluno');
