-- USE DATABASE projeto
USE projeto
-- DELETE RECORDS FROM problema
DELETE FROM problema;
-- INSERT INTO problema
INSERT INTO problema VALUES ('1','1','Botão direito do mouse nao funciona no lab 3 maquina BRJ40928','1','2017-05-13','3');
INSERT INTO problema VALUES ('2','3','Monitor do lab 1 não está ligando, maquina JRC31948','2','2017-05-15','4');
INSERT INTO problema VALUES ('3','4','Teclado com problema no lab 1 maquina GRT80238','3','2017-03-01','3');
INSERT INTO problema VALUES ('4','5','Software ASTAH não esta funcionando no lab 4 maquina IOU56912','4','2017-03-04','6');
INSERT INTO problema VALUES ('5','2','CPU não está ligando no lab 2 maquina RTW58701','5','2017-05-10','5');
INSERT INTO problema VALUES ('6','6','Cabo está com mau contato e o pc está desligando','5','2017-05-15','6');
